# Generated by Django 5.2.7 on 2026-06-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactUs',
        ),
    ]
